import type { Product } from "./types"

// Sample data
export const sampleProducts: Product[] = [
  {
    id: "1",
    name: "Premium Hoodie",
    category: "Clothing",
    price: 85,
    rating: 4.8,
    stock: 24,
    status: ["Featured", "Active"],
    image: "/images/store/tanjiro.jpg?height=200&width=200",
  },
  {
    id: "2",
    name: "Urban Sneakers",
    category: "Clothing",
    price: 120,
    rating: 4.5,
    stock: 12,
    status: ["Featured", "Active"],
    image: "/images/store/1.jpg?height=200&width=200",
  },
  {
    id: "3",
    name: "Graphic T-Shirt",
    category: "Clothing",
    price: 35,
    rating: 4.2,
    stock: 42,
    status: ["Active"],
    image: "/images/store/2.jpg?height=200&width=200",
  },
  {
    id: "4",
    name: "Minimalist Watch",
    category: "Clothing",
    price: 95,
    rating: 4.7,
    stock: 8,
    status: ["Active"],    
    image: "/images/store/3.jpg?height=200&width=200",

  },
  {
    id: "5",
    name: "Leather Wallet",
    category: "Clothing",
    price: 65,
    rating: 4.6,
    stock: 0,
    status: ["Out of Stock"],
    image: "/images/store/4.jpg?height=200&width=200",
  },
  {
    id: "6",
    name: "Summer Collection Shirt",
    category: "Clothing",
    price: 45,
    rating: 0,
    stock: 10,
    status: ["Draft"],
    image: "/images/store/5.jpg?height=200&width=200",

  },
  {
    id: "7",
    name: "Designer Sunglasses",
    category: "Clothing",
    price: 75,
    rating: 4.9,
    stock: 5,
    status: ["Featured", "Active"],
    image: "/images/store/6.jpg?height=200&width=200",
  },
  {
    id: "8",
    name: "Wireless Earbuds",
    category: "Clothing",
    price: 110,
    rating: 4.4,
    stock: 15,
    status: ["Active"],
    image: "/images/store/tanjiro.jpg?height=200&width=200",
  },
]
