import { Invoice } from '../types';

export const MOCK_INVOICES: Invoice[] = [
  {
    id: '1',
    invoiceNumber: 'INV-2024-001',
    company: 'Premium Hoodie (Black)',
    description: 'Urban Style Store • March 15, 2024',
    date: 'INV-2024-001',
    invoiceDate: 'March 15, 2024',
    dueDate: 'March 22, 2024',
    amount: '85 XLM',
    status: 'Paid',
    items: [
      {
        name: 'Premium Hoodie (Black)',
        description: 'Size: L, Qty: 1',
        amount: '80 XLM',
      },
      {
        name: 'Shipping',
        description: 'Standard delivery',
        amount: '5 XLM',
      },
    ],
    subtotal: '80 XLM',
    shipping: '5 XLM',
    tax: '0 XLM',
    total: '85 XLM',
    paymentReceived: true,
    paymentDate: 'March 15, 2024',
    paymentMethod: 'Stellar XLM',
    transactionId: 'TX123456789',
    billingInfo: {
      name: 'Urban Dealer',
      company: 'Urban Style Co.',
      address: 'Blockchain Avenue, BC 12345',
      location: 'Stellar Address: GBQR...AQT1.4',
    },
  },
  {
    id: '2',
    invoiceNumber: 'INV-2024-002',
    company: 'Urban Sneakers (Gray)',
    description: 'Sneaker Haven • March 16, 2024',
    date: 'INV-2024-002',
    invoiceDate: 'March 16, 2024',
    dueDate: 'March 23, 2024',
    amount: '120 XLM',
    status: 'Paid',
    items: [
      {
        name: 'Urban Sneakers (Gray)',
        description: 'Size: 42, Qty: 1',
        amount: '115 XLM',
      },
      {
        name: 'Shipping',
        description: 'Express delivery',
        amount: '5 XLM',
      },
    ],
    subtotal: '115 XLM',
    shipping: '5 XLM',
    tax: '0 XLM',
    total: '120 XLM',
    paymentReceived: true,
    paymentDate: 'March 16, 2024',
    paymentMethod: 'Stellar XLM',
    transactionId: 'TX987654321',
    billingInfo: {
      name: 'Sneaker Dealer',
      company: 'Sneaker Haven Inc.',
      address: 'Fashion Street, FC 67890',
      location: 'Stellar Address: GCXY...BRT2.1',
    },
  },
  {
    id: '3',
    invoiceNumber: 'INV-2024-003',
    company: 'Wireless Earbuds',
    description: 'Tech Gadgets • March 5, 2024',
    date: 'INV-2024-003',
    invoiceDate: 'March 5, 2024',
    dueDate: 'March 12, 2024',
    amount: '75 XLM',
    status: 'Pending',
    items: [
      {
        name: 'Wireless Earbuds',
        description: 'Model: WE-2024, Qty: 1',
        amount: '70 XLM',
      },
      {
        name: 'Shipping',
        description: 'Standard delivery',
        amount: '5 XLM',
      },
    ],
    subtotal: '70 XLM',
    shipping: '5 XLM',
    tax: '0 XLM',
    total: '75 XLM',
    billingInfo: {
      name: 'Tech Dealer',
      company: 'Tech Gadgets Ltd.',
      address: 'Innovation Hub, IH 11111',
      location: 'Stellar Address: GDEF...CRT3.7',
    },
  },
  {
    id: '4',
    invoiceNumber: 'INV-2024-004',
    company: 'Sustainable Water Bottle',
    description: 'Eco Friendly Store • March 28, 2024',
    date: 'INV-2024-004',
    invoiceDate: 'March 28, 2024',
    dueDate: 'April 4, 2024',
    amount: '25 XLM',
    status: 'Overdue',
    items: [
      {
        name: 'Sustainable Water Bottle',
        description: 'Eco-friendly, 500ml',
        amount: '20 XLM',
      },
      {
        name: 'Shipping',
        description: 'Standard delivery',
        amount: '5 XLM',
      },
    ],
    subtotal: '20 XLM',
    shipping: '5 XLM',
    tax: '0 XLM',
    total: '25 XLM',
    billingInfo: {
      name: 'Eco Dealer',
      company: 'Eco Friendly Store',
      address: 'Green Valley, GV 22222',
      location: 'Stellar Address: GHIJ...DRT4.2',
    },
  },
];
