import { Ticket } from "../types/ticket"

// Mock data updated to match mockup
export const mockTickets: Ticket[] = [
  {
    id: "TK-1234",
    date: "Mar 15, 2024",
    title: "Payment Processing Issue",
    status: "Open",
    priority: "High",
    category: "Billing",
    lastUpdated: "2 hours ago",
    commentCount: 3,
  },
  {
    id: "TK-1233",
    date: "Mar 14, 2024",
    title: "Product Upload Error",
    status: "In Progress",
    priority: "Medium",
    category: "Technical",
    lastUpdated: "1 day ago",
    commentCount: 5,
  },
  {
    id: "TK-1232",
    date: "Mar 13, 2024",
    title: "Store Settings Update",
    status: "In Progress",
    priority: "Low",
    category: "Account",
    lastUpdated: "2 days ago",
    commentCount: 2,
  },
  {
    id: "TK-1231",
    date: "Mar 12, 2024",
    title: "API Integration Help",
    status: "Resolved",
    priority: "Medium",
    category: "Technical",
    lastUpdated: "3 days ago",
    commentCount: 8,
  },
  {
    id: "TK-1230",
    date: "Mar 11, 2024",
    title: "Refund Request for Order #45678",
    status: "Open",
    priority: "High",
    category: "Billing",
    lastUpdated: "4 days ago",
    commentCount: 2,
  },
] 